### PR TITLE
0.7.0 Could you please publish it as soon as possible? 

### PR DESCRIPTION
**Pull request by GermanBluefox**
* (bluefox) Fixed the ID select dialog in Admin3
* (bluefox) Replace grunt with gulp

Could you please publish it as soon as possible? 
People wont use Admin 3 because Select ID dialog does not work. :(

Thank you.

### CODE REVIEW

**Comment by jensweigele** [comment]
Sorry, but these are too many changes at once (Gulp, Admin3, newer Dependencies).
I will try to divide them into single commits and only merge the necessary changes.
I would also appreciate if we don't reformat the code files with every commit (different editors have different code formatings - for this small projects it's easier to just keep the formating).

**Comment by GermanBluefox** [comment]
No problem.
The very important change is:
only this:
https://github.com/GermanBluefox/ioBroker.yahka/blob/master/admin/index_m.html
and this:
https://github.com/GermanBluefox/ioBroker.yahka/blob/master/io-package.json#L57

If you can merge it, it would be nice for the first step.

2018-01-31 21:44 GMT+01:00 jensweigele <notifications@github.com>:

**Comment by jensweigele** [comment]
Thx for the work!
I really only merged the necessary changes. Will have a look at the Gulp Integration on another day.
The adapter in Version 0.7.0 is published on npm.

**Comment by GermanBluefox** [comment]
Thank you too.
I have a couple of question concerning formatting for the future requests:
I do formatting just in the brain background and sometimes even do not notice that. :)
But is it OK?
1. var => let?
2. " => ' (because I can see you use sometimes ", and sometimes ')

I will prepare the PR with words.js because it is just the extend of file and nothing more.

**Pull request closed without merging**
