### PR TITLE
Add AVAHI advertiser as default

### PR DESCRIPTION
**Pull request by TA2k**
Add AVAHI advertiser as default advertiser.
Supported since hap-nodejs 0.10
If not AVAHI advertiser is available hap-nodejs fallback to ciao

### CODE REVIEW

**Comment by Apollon77** [comment]
LGTM
@jensweigele @GermanBluefox please accept and release

**Comment by jensweigele** [comment]
Thanks for submitting that PR!
Can you please undo all the formatting changes? That makes it much easier to review the changes.

**Comment by TA2k** [comment]
Here you can see the changes not formatting changes
https://github.com/jensweigele/ioBroker.yahka/pull/350/commits/ad8e3b6a0d64db22b00be9a4fdaca822ee7933ec

**Comment by TA2k** [comment]
@jensweigele can you have a look again on the PR

**Comment by TA2k** [comment]
@GermanBluefox Can you please have a look and release a new version

**Comment by jensweigele** [comment]
I reverted the push since it looks like it broke the software (see #359)

**Comment by jensweigele** [comment]
Just saw that someone also published that broken version to NPM - I'm going to release a 0.16 to revert the changes...

**Pull request merged**
